#!/bin/sh

cli_json="akamai-cli.config.json"
edgeworkerId=`cat ${cli_json} | jq -r '.edgeworkers.edgeworkerId'`
edgeworkerBundleVersion=`cat dist/bundle.json | jq -r '.["edgeworker-version"]'`

cat $1 | sed "s;@@VERSION@@;${edgeworkerBundleVersion};" | sed "s;@@EDGEWORKERS_ID@@;${edgeworkerId};" > $1.new
mv $1 $1.orig
mv $1.new $1
